name: ecodrive
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  url_launcher: ^6.1.7
  geolocator: ^9.0.2
  font_awesome_flutter: ^10.3.0


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

